version: '3.4'
services:
    zookeeper:
        image: zookeeper
        restart: always
        ports:
            - 2181:2181
        networks:
            - kafka-network
    kafka:
        image: confluentinc/cp-kafka
        restart: always
        ports:
            - 9092:9092
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.13:9092
            KAFKA_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        depends_on:
            - zookeeper
        networks:
            - kafka-network
    elasticsearch:
        image: elasticsearch:7.6.1
        restart: always
        environment:
            - node.name=elasticsearch
            - discovery.seed_hosts=elasticsearch
            - cluster.initial_master_nodes=elasticsearch
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            # For development
            #- discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports: 
            - 9200:9200
              #- 9300:9300
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        networks:
            - kafka-network
    kibana:
        image: kibana:7.6.1
        ports:
            - 5601:5601
        environment:
            - "ELASTICSEARCH_URL=http://elasticsearch:9200"
        depends_on:
            - elasticsearch
        networks:
            - kafka-network
    logstash:
        image: logstash:7.6.1
        volumes:
            - ./:/config-dir
        command: logstash -f /config-dir/logstash.conf
        depends_on:
            - elasticsearch
            - kafka
        networks:
            - kafka-network
networks:
    kafka-network:
        driver: bridge
volumes:
  elasticsearch-data:
